### ISSUE TITLE
Built-in import action not working

### ISSUE THREAD

**Issue by jemayn** [umbraco/Umbraco.UIBuilder.Issues#55]
**Describe the bug**
When I add the [KonstruktImportEntityAction](https://docs.getkonstrukt.net/actions/inbuilt-actions), it gets added to the context menu just fine. However when I click it I get an error.

**Steps To Reproduce**
1. Add a collection with the import action
2. Go to the action dropdown on the page, and click the import button

**Expected behavior**
I'd expect a file upload field to show.

**Screenshots**
I click the action here:
![image](https://user-images.githubusercontent.com/79840720/223150479-ac212616-4715-44f8-83a3-7a5ae0ea168e.png)
It gives me this error in a popup:
![image](https://user-images.githubusercontent.com/79840720/223150648-d4ae9c17-7ca5-48a7-a52e-feacb3bedeeb.png)

**Environment (please complete the following information):**
 - Server OS: IIS Express on a Windows 11 machine
 - Browser: Edge Version 110.0.1587.57 (Officielt build) (64-bit)
 - Umbraco Version 11.2.0
 - Product Version 1.6.4

**Additional context**
All I did was add this to my collection:
```csharp
.AddCollection<LocalizationView>(x => x.Id, "Localization", "Localizations",
                        "Translated dictionary items", collectionConfig => collectionConfig
    .SetRepositoryType<LocalizationRepository>()
    .AddAction<KonstruktExportEntityAction>()
    .AddAction<KonstruktImportEntityAction>()
```

The full error message:

```log
An error occurred
No data type found with the Name: Upload File

Exception Details
System.ApplicationException, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: No data type found with the Name: Upload File
Stacktrace
at Konstrukt.Web.Helpers.UmbracoDataTypeHelper.<>c__DisplayClass5_0.<ResolveDataType>b__0()
   at Umbraco.Extensions.AppCacheExtensions.<>c__DisplayClass5_0`1.<GetCacheItem>b__0()
   at Umbraco.Cms.Core.Cache.SafeLazy.<>c__DisplayClass1_0.<GetSafeLazy>b__0()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Core.Cache.ObjectCacheAppCache.Get(String key, Func`1 factory, Nullable`1 timeout, Boolean isSliding, String[] dependentFiles)
   at Umbraco.Cms.Core.Cache.ObjectCacheAppCache.Get(String key, Func`1 factory)
   at Umbraco.Cms.Core.Cache.DeepCloneAppCache.Get(String key, Func`1 factory)
   at Umbraco.Extensions.AppCacheExtensions.GetCacheItem[T](IAppCache provider, String cacheKey, Func`1 getCacheItem)
   at Konstrukt.Web.Helpers.UmbracoDataTypeHelper.ResolveDataType(String dataTypeName, Boolean isReadOnly)
   at Konstrukt.Web.Helpers.UmbracoDataTypeHelper.ResolveDataType(DataTypeReference dataTypeRef, Boolean isReadOnly)
   at Konstrukt.Web.Models.Mappers.UmbracoPropertyMapper.ToContentPropertyDisplayModel(DataTypeReference dataTypeRef, Int32 id, String alias, String label, String description, Object value, Boolean isRequired, String regexPattern, Boolean hideLabel, Boolean isReadOnly)
   at Konstrukt.Web.Models.Mappers.KonstruktEditorMapper.ToEditModel(EditModelMappingContext ctx)
   at Konstrukt.Web.Models.Mappers.KonstruktSettingsMapper.ToEditModel(EditModelMappingContext ctx)
   at Konstrukt.Web.Controllers.Api.KonstruktApiController.GetSettingsScaffold(String collectionAlias, String settingsSourceType, String settingsSourceAlias)
   at lambda_method1637(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

---
_This item has been added to our backlog AB#34770_

**Comment by mattbrailsford** [comment]
Is there a data type named "Upload File" in the settings section? Maybe Umbraco changed the default names 🤔

**Comment by jemayn** [comment]
I guess this is the one?
![image](https://user-images.githubusercontent.com/79840720/223369558-2a00836f-7e28-4db7-8684-371b96cceb7a.png)

This is also a migrated v7 -> 11 project, so could be part of the reason.

After renaming the datatype to "Upload File" it works - although maybe there is a better way than checking on the string name? 🙂

Either way my immediate problem is solved, so if you want to close this feel free. Thanks for the quick help!

**Comment by mattbrailsford** [comment]
Yea, I may need to check to see if it has the same ID as the old "File Upload". If so, it might be better for us to code that to the upload field instead.
